config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  get "/tasks/:id", to: "tasks#show", as: "task"
  get "/tasks/:id/edit", to: "tasks#edit", as: "edit"
  patch "/tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9a0d52641d.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task <%= @task.title %></h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
  <h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <% if task.completed? %>
    <li>   <i class="far fa-check-square"></i>
 <%= link_to task.title, task_path(task) %> <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="bi bi-trash"></i>
<% end %></li>
    <% else %>
    <li> <i class="far fa-square"></i> <%= link_to task.title, task_path(task) %> <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
  <i class="bi bi-trash"></i>
<% end %></li>
    <% end %>

  <% end %>
</ul>


<%= link_to tasks_new_path do %>
  <i class="bi bi-plus-square"></i> Add new task
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "Edit this task", edit_path(@task), :class => "btn btn-primary"%>

<ul>
  <li>Details: <strong><%= @task.details %></strong></li>
</ul>
<% if @task.completed? %> </p>
<i class="far fa-check-square"> <p> This task has been completed
<% else %>
<i class="far fa-square"> <p>This task has not been completed</p>
<% end %>

<div>
<%= link_to tasks_path do %>
  <i class="fas fa-history"></i>
Back to list
<% end %>
</div>